In [1]:
import pandas as pd

In [2]:
series = pd.Series(["Toyota", "BMW", "Mercedes Benz", "Rolls Royce", "Hyundai", "Honda"])

In [3]:
series

0           Toyota
1              BMW
2    Mercedes Benz
3      Rolls Royce
4          Hyundai
5            Honda
dtype: str

In [4]:
colours = pd.Series(["Red", "Brown", "Orange", "Blue", "Pink", "Black", "White"])

In [5]:
colours

0       Red
1     Brown
2    Orange
3      Blue
4      Pink
5     Black
6     White
dtype: str

In [8]:
dataframe = pd.DataFrame({"Cars": ["BMW", "Honda", "Porche", "Rolls Royce", "Range Rover", "Jeep", "Bentley"], "Colour": ["Black", "White", "Red", "Blue", "Brown", "Yellow", "Pink"]})

dataframe

          Cars  Colour
0          BMW   Black
1        Honda   White
2       Porche     Red
3  Rolls Royce    Blue
4  Range Rover   Brown
5         Jeep  Yellow
6      Bentley    Pink

In [10]:
# Import data
cars_sale = pd.read_csv("../data/car-sales.csv")

cars_sale

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00